name: Deploy Node Application

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t jhondel/bulsujuans-backend-app:latest .

      - name: Publish Image to Docker Hub
        run: docker push jhondel/bulsujuans-backend-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull jhondel/bulsujuans-backend-app:latest

      # - name: Delete Old Container
      #   run: docker rm -f bulsujuans-backend-app-container || true

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
          echo "NODEMAILER_GMAIL=${{ secrets.NODEMAILER_GMAIL }}" >> .env
          echo "NODEMAILER_PASSWORD=${{ secrets.NODEMAILER_PASSWORD }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
        shell: bash

      - name: Start app with Docker Compose
        run: docker-compose up -d

      # - name: Run Prisma Migrate
      #   run: |
      #     docker run --rm \
      #       --env-file .env \
      #       jhondel/bulsujuans-backend-app:latest \
      #       npx prisma migrate deploy

      # - name: Run Docker Container
      #   run: docker run -d -p 4000:4000 \
      #     --name bulsujuans-backend-app-container \
      #     --env-file .env \
      #     jhondel/bulsujuans-backend-app:latest
